const docs = [
  ['Cell Biology & Genetics.pdf','Learning material · 124 pages'],
  ['Human Physiology Notes.pdf','Learning material · 86 pages'],
  ['General Chemistry IMAT.pdf','Learning material · 102 pages'],
  ['IMAT 2024 Past Paper.pdf','Style reference · 16 pages']
];
const cards = [
  ['What is the primary role of DNA polymerase during replication?','DNA polymerase synthesises a new DNA strand by adding complementary nucleotides to the 3′ end of the growing strand.'],
  ['Which phase of the cell cycle includes DNA replication?','DNA replication takes place during the S phase of interphase.'],
  ['What is the function of messenger RNA?','mRNA carries genetic instructions copied from DNA to ribosomes, where proteins are made.'],
  ['What does semiconservative replication mean?','Each new DNA double helix contains one original strand and one newly synthesised strand.']
];
let cardIndex=0;
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function showView(name){$$('.view').forEach(x=>x.classList.remove('active-view')); $(`#${name}View`).classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name)); const titles={home:'Good morning, Khalid',library:'Learning library',flashcards:'Flashcards',practice:'Practice tests',progress:'Progress'};$('#pageTitle').innerHTML=titles[name]+(name==='home'?' <span>✦</span>':'');window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
function renderDocs(){ $('#docGrid').innerHTML=docs.map((d,i)=>`<article class="doc-card"><div class="file-icon pdf">PDF</div><div><b>${d[0]}</b><small>${d[1]}</small></div><button title="Remove document" data-remove="${i}">×</button></article>`).join('');$('#docCount').textContent=String(docs.length).padStart(2,'0');$$('[data-remove]').forEach(b=>b.onclick=()=>{docs.splice(+b.dataset.remove,1);renderDocs();toast('Document removed from this workspace')})}renderDocs();
const input=$('#pdfInput');$('#uploadBtn').onclick=()=>input.click();$('#browseLink').onclick=()=>input.click();input.onchange=e=>addFiles(e.target.files);function addFiles(files){const incoming=[...files].filter(x=>x.type==='application/pdf');if(!incoming.length)return toast('Please choose PDF files only');const slots=20-docs.length;incoming.slice(0,slots).forEach(f=>docs.push([f.name,`Learning material · ${(f.size/1048576).toFixed(1)} MB`]));renderDocs();toast(`${Math.min(incoming.length,slots)} document${Math.min(incoming.length,slots)>1?'s':''} added — ready to generate from`);if(incoming.length>slots)toast('Your workspace can contain up to 20 PDFs')}
const drop=$('#dropZone');drop.ondragover=e=>{e.preventDefault();drop.style.background='#f3f1ff'};drop.ondragleave=()=>drop.style.background='';drop.ondrop=e=>{e.preventDefault();drop.style.background='';addFiles(e.dataTransfer.files)};
function renderCard(){const [q,a]=cards[cardIndex%cards.length];$('#cardNum').textContent=cardIndex+1;$('#cardQuestion').textContent=q;$('#cardAnswer').querySelector('p').textContent=a;$('#flashcard').classList.remove('revealed')}$('#flashcard').onclick=()=>$('#flashcard').classList.toggle('revealed');$('#nextCard').onclick=()=>{cardIndex=(cardIndex+1)%cards.length;renderCard()};$('#prevCard').onclick=()=>{cardIndex=(cardIndex+cards.length-1)%cards.length;renderCard()};$$('[data-rate]').forEach(b=>b.onclick=()=>{toast(`Marked ${b.dataset.rate}. Your review schedule has been updated.`);cardIndex=(cardIndex+1)%cards.length;renderCard()});
const qBank=[
 ['During DNA replication, which enzyme joins Okazaki fragments on the lagging strand?',['DNA ligase','DNA polymerase','Helicase','Primase'],0],
 ['A cell placed in a hypertonic solution will most likely:',['Gain water and swell','Lose water and shrink','Remain unchanged','Divide rapidly'],1],
 ['Which organelle is primarily responsible for ATP production in eukaryotic cells?',['Ribosome','Golgi apparatus','Mitochondrion','Lysosome'],2],
 ['What is the probability that a child of two heterozygous parents (Aa × Aa) has genotype aa?',['0%','25%','50%','75%'],1],
 ['Which vessel carries oxygenated blood from the lungs to the heart?',['Pulmonary artery','Aorta','Vena cava','Pulmonary vein'],3],
 ['The pH of a neutral aqueous solution at 25°C is:',['0','7','10','14'],1]
];
$('#generateTest').onclick=()=>{const count=+$('#questionCount').value;const qs=Array.from({length:count},(_,i)=>qBank[i%qBank.length]);$('#examArea').innerHTML=`<section class="exam"><div class="exam-header"><div><h3>${$('#testName').value||'Untitled practice test'}</h3><p>${count} questions · Cell biology, genetics & physiology · Original questions grounded in your library</p></div><div class="timer">30:00</div></div><div id="questions">${qs.map((q,i)=>`<div class="question"><b>${i+1}. ${q[0]}</b><div class="options">${q[1].map((o,j)=>`<button class="option" data-q="${i}" data-answer="${j}"><b>${String.fromCharCode(65+j)}.</b> ${o}</button>`).join('')}</div></div>`).join('')}</div><button class="dark-btn wide" id="submitTest">Submit & evaluate <span>→</span></button></section>`;const answers={};$$('.option').forEach(b=>b.onclick=()=>{answers[b.dataset.q]=+b.dataset.answer;$$(`.option[data-q="${b.dataset.q}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('#submitTest').onclick=()=>{const correct=+$('#correctMark').value||1,wrong=+$('#negativeMark').value||0,pass=+$('#passMark').value||0;let right=0,incorrect=0;qs.forEach((q,i)=>answers[i]===undefined?0:answers[i]===q[2]?right++:incorrect++);const raw=right*correct+incorrect*wrong;const max=count*correct;const pct=Math.max(0,raw/max*100);$('#examArea').insertAdjacentHTML('beforeend',`<div class="result"><strong>${pct.toFixed(1)}%</strong><p><b>${pct>=pass?'You passed — great work!':'Keep going — you are getting there.'}</b><br>${right} correct · ${incorrect} incorrect · ${count-right-incorrect} unanswered<br>Score: ${raw.toFixed(2)} / ${max.toFixed(2)} marks · Pass mark: ${pass}%</p></div>`);$('#submitTest').disabled=true;$('#submitTest').style.opacity='.55';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})};$('#examArea').scrollIntoView({behavior:'smooth',block:'start'})};
